### ISSUE TITLE
Issue with the "using_index" puzzle?

### ISSUE THREAD

**Issue by sev2109** [learn-co-curriculum/intro-to-simple-array-manipulations#19]
Hey!
I'm one of the teachers in the fellowship working on this lab.

The using_insert puzzle spec says that method should:
  takes in two arguments, an array and a new element to be added to the array. it uses the insert method to add the new element to the 4th index of the array

Thinking that the 4th index of the array was actually labeled 3 (0, 1, 2, 3), I specified the index as 3 in the code: new_array = list_of_esoteric_programming_languages.insert(3, another_esoteric_language).

That was flagged as a failure when I ran the test
Failure/Error: expect(@new_array[4]).to eq(@another_esoteric_language)
       expected: "Malbolge"
            got: "Binary lambda calculus"

I corrected it to 4 and the test passed but it seems like it should be 3, no?
Sara

**Comment by JoanBrownCS** [comment]
Index is the actual number to type into the code. The index of 4 accesses the 5th element in the array.
