### ISSUE TITLE
Changing the size of the input array.

### ISSUE THREAD

**Issue by JoanBrownCS** [learn-co-curriculum/intro-to-simple-array-manipulations#20]
I might have missed something, but this lesson wants you to have a method change the size of the input array. I checked the documentation for methods and do not see a way to have a parameter be in/out. I changed my spec file to fix this problem.
![spec modification](https://cloud.githubusercontent.com/assets/15305066/11609338/7231341e-9b41-11e5-9320-842f622c1e2a.PNG)

**Comment by AnnJohn** [comment]
Hi @JoanBrownCS is this still an issue? The best way to get help is to use the Ask a Question function in Learn. The spec in this case is saying that the method will increase the elements in the array, and using the concat function will do that. And the solution therefore will be:

def using_concat(array1, array2)
  array1.concat(array2)
end

thanks!
