### ISSUE TITLE
Can't pull request, getting a 403

### ISSUE THREAD

**Issue by BettinaP** [learn-co-curriculum/intro-to-simple-array-manipulations#21]
Hello,

I can't seem to git push this lab so I can create a pull request. It keeps asking me for my github.com login info in the terminal and denying me access to learn.co/intro-to-simple arrays. All my other labs are pushing through fine.

Please advise.

Thank you,
Bettina

**Comment by AnnJohn** [comment]
hi @BettinaP sorry for the delay with this. This is a technical issue so for immediate help please use the Ask a Question tool and someone from our support team will help you out, if this is still an issue. You can also file a bug report for this- if you hover over your profile pic in Learn a menu will pop up and you'll see an option there to Report a Bug. Thanks!
