### ISSUE TITLE
Error in test for pop_with_args method

### ISSUE THREAD

**Issue by yakovkiff** [learn-co-curriculum/intro-to-simple-array-manipulations#24]
The test refers to Sandor Clegane as the Mountain, this is factually incorrect.  Gregor Clegane is the Mountain, duh.

**Comment by Porzingod** [comment]
The test wants us to pop twice but to get desired array we need to shift twice.

**Comment by morgvanny** [comment]
The first issue is resolved. Thanks for that clarification.

@Porzingod I'm unable to reproduce your issue. If that file is saved, then your pop_with_args(array) method should actually just be returning 2, and not an array at all. Your test output is saying that it's returning ["Danny T", "Tyrion Lannister"], which must be from some other code not pictured. If you want clarification on this exercise, feel free to use the Ask a Question feature on the site.

Happy coding!
